GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaXpreSBMdWJpcyIsImVtYWlsIjoibXVoYW1tYWRyaXpreWx1YmlzQHN0dWRlbnRzLnBvbG1lZC5hYy5pZCIsImlhdCI6MTcwMjk5NDc4OCwiZXhwIjoxNzAzMDE2Mzg4fQ.2mLcykpLkHZ7O6_oaSq5Hd8OloThHh2rPpdnEYikyN0


### Register
POST http://localhost:5000/register
Content-Type: application/json

{
  "fullname": "Muhammad Rizky Lubis",
  "email": "muhammadrizkylubisz@students.polmed.ac.id",
  "password": "Akagami5321!@#",
  "confirmPassword": "Akagami5321!@#"
}

### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "muhammadrizkylubis@students.polmed.ac.id",
  "password": "Akagami5321!@#"
}

### Get Refresh Token  
GET http://localhost:5000/refresh-token
Content-Type: application/json


### Get Course By Id
GET http://localhost:5000/course/1
Content-Type: application/json



### Logout
DELETE  http://localhost:5000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExMiwibmFtZSI6Ik1VSEFNTUFEIFJJWktZIExVQklTIiwiZW1haWwiOiJtdWhhbW1hZHJpemt5bHViaXNAc3R1ZGVudHMucG9sbWVkLmFjLmlkIiwiaWF0IjoxNzAzMDYyNDcxLCJleHAiOjE3MDMxNDg4NzF9._t-B2-43Yvgbsar0EwwNeUo8h_b1MF1n4ImkH92_jXU
Content-Type: application/json

{
  "userId": 112
}



### Courses
POST http://localhost:5000/add-course
Content-Type: application/json


 {
  "title": "Marketing Introduction",
  "link": "https://myskill.id/course/marketing-introduction",
  "organizer": "Myskill",
  "category": "Digital Marketing",
  "instructor": "Ryan Dwana",
  "level": "Beginner ",
  "rating": "4.66",
  "fee": "Berbayar",
  "description": "Dalam materi ini kamu akan belajar secara dasar dalam melakukan penempatan btrand. Kamu juga akan diberi pemahaman betapa pentingnya penempatan brand kepada konsumen kamu untuk meningkatkan daya tarik pada brand kamu. Serta kamu juga akan mempelajari bagaimana cara untuk membuat penempatan brand yang kuat dalam memastikan efektivitas pasar."
 }