GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsIm5hbWUiOiJNdWhhbW1hZCBSaXpreSBMdWJpcyIsImVtYWlsIjoibXVoYW1tYWRyaXpreWx1YmlzQHN0dWRlbnRzLnBvbG1lZC5hYy5pZCIsImlhdCI6MTcwMjc5MjA5MywiZXhwIjoxNzAyNzkyMTIzfQ.KjdBBa1xCTDBYB4djiHguAw8Kc8Chl9aH_eQe7jTCoI



### Register
POST http://localhost:5000/register
Content-Type: application/json

{
  "fullname": "Muhammad Rizky Lubis",
  "email": "muhammadrizkylubisz@students.polmed.ac.id",
  "password": "Akagami5321!@#",
  "confirmPassword": "Akagami5321!@#"
}

### login
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "muhammadrizkylubis@students.polmed.ac.id",
  "password": "Akagami5321!@#"
}

### Get Refresh Token  
GET http://localhost:5000/refresh-token

### Logout
DELETE http://localhost:5000/logout



### Courses
POST http://localhost:5000/add-course
Content-Type: application/json


 {
  "title": "Marketing Introduction",
  "link": "https://myskill.id/course/marketing-introduction",
  "organizer": "Myskill",
  "category": "Digital Marketing",
  "instructor": "Ryan Dwana",
  "level": "Beginner ",
  "rating": "4.66",
  "fee": "Berbayar",
  "description": "Dalam materi ini kamu akan belajar secara dasar dalam melakukan penempatan btrand. Kamu juga akan diberi pemahaman betapa pentingnya penempatan brand kepada konsumen kamu untuk meningkatkan daya tarik pada brand kamu. Serta kamu juga akan mempelajari bagaimana cara untuk membuat penempatan brand yang kuat dalam memastikan efektivitas pasar."
 }